In [15]:
import requests
import pandas as pd
import os

In [16]:
AllCourses = requests.get("https://mario-kart-tour-api.herokuapp.com/api/v1/courses/")
AllDrivers = requests.get("https://mario-kart-tour-api.herokuapp.com/api/v1/drivers/")

In [17]:
#Gather the course data
#Request into JSON
CourseData = AllCourses.json()
# JSON Data to Dataframe
courses_df = pd.DataFrame(CourseData)
#Show the DF
courses_df

,name,debut_tour,date_added,debut_game,debut_system,is_ranked_week_1,is_ranked_week_2,is_reverse,is_trick,level_one_top_shelf_drivers,level_three_top_shelf_drivers,level_six_top_shelf_drivers
0,3DS Cheep Cheep Lagoon,New York Tour,2019-09-25T00:00:00.000Z,Mario Kart 7,3DS,False,False,False,False,"[{'id': 2, 'name': 'Baby Peach', 'rarity': 'No...",[],"[{'id': 60, 'name': 'Mario (Happi)', 'rarity':..."
1,3DS Cheep Cheep Lagoon R,New York Tour,2019-09-25T00:00:00.000Z,Mario Kart 7,3DS,False,False,True,False,"[{'id': 11, 'name': 'Lemmy', 'rarity': 'Normal...","[{'id': 54, 'name': 'Peach (Vacation)', 'rarit...",[]
2,3DS Cheep Cheep Lagoon R/T,Holiday Tour,2019-12-18T00:00:00.000Z,Mario Kart 7,3DS,False,False,True,True,"[{'id': 6, 'name': 'Koopa Troopa', 'rarity': '...","[{'id': 38, 'name': 'Pink Shy Guy', 'rarity': ...","[{'id': 10, 'name': 'Larry', 'rarity': 'Normal..."
3,3DS Cheep Cheep Lagoon T,New York Tour,2019-09-25T00:00:00.000Z,Mario Kart 7,3DS,False,False,False,True,"[{'id': 16, 'name': 'Mario', 'rarity': 'Super'...",[],"[{'id': 70, 'name': 'Yoshi (Egg Hunt)', 'rarit..."
4,3DS Daisy Hills,New York Tour,2019-09-25T00:00:00.000Z,Mario Kart 7,3DS,False,False,False,False,"[{'id': 19, 'name': 'Daisy', 'rarity': 'Super'...","[{'id': 69, 'name': 'Baby Rosalina (Detective)...",[]
...,...,...,...,...,...,...,...,...,...,...,...,...
217,Wii DK Summit R,Snow Tour,2021-02-24T00:00:00.000Z,Mario Kart Wii,Wii,False,False,True,False,"[{'id': 71, 'name': 'Black Yoshi', 'rarity': '...",[],"[{'id': 93, 'name': 'Penguin Toad', 'rarity': ..."
218,Wii DK Summit T,Snow Tour,2021-02-24T00:00:00.000Z,Mario Kart Wii,Wii,False,False,False,True,"[{'id': 73, 'name': 'Builder Toad', 'rarity': ...",[],[]
219,Wii Maple Treeway,Halloween Tour (2020),2020-10-21T00:00:00.000Z,Mario Kart Wii,Wii,False,False,False,False,"[{'id': 61, 'name': 'Toad (Party Time)', 'rari...",[],"[{'id': 114, 'name': 'Shy Guy (Gold)', 'rarity..."
220,Wii Maple Treeway R,Halloween Tour (2020),2020-10-21T00:00:00.000Z,Mario Kart Wii,Wii,False,False,True,False,"[{'id': 25, 'name': 'Red Yoshi', 'rarity': 'Su...","[{'id': 85, 'name': 'Peach (Halloween)', 'rari...",[]
221,Wii Maple Treeway T,Halloween Tour (2020),2020-10-21T00:00:00.000Z,Mario Kart Wii,Wii,False,False,False,True,"[{'id': 68, 'name': 'Luigi (Classic)', 'rarity...","[{'id': 90, 'name': 'Cat Peach', 'rarity': 'Hi...","[{'id': 84, 'name': 'Mario (Halloween)', 'rari..."

In [18]:
#Create our DriverDF
#Gather the Driver data
DriverData = AllDrivers.json()
drivers_df = pd.DataFrame(DriverData)
drivers_df

,position,name,rarity,special_skill,debut_tour,date_added,level_one_favorite_courses,level_three_favorite_courses,level_six_favorite_courses,is_daily_select,...,helmet,horns,kong,koopaling,mustache,ribbon,shell,short_sleeves,three_hairs,tie
0,1,Baby Mario,Normal,Boomerang Flower,New York Tour,2019-09-25T00:00:00.000Z,"[{'id': 60, 'name': 'DS Waluigi Pinball', 'deb...",[],"[{'id': 143, 'name': 'SNES Vanilla Lake 1R/T',...",True,...,False,False,False,False,False,False,False,False,False,False
1,2,Baby Peach,Normal,Bubble,New York Tour,2019-09-25T00:00:00.000Z,"[{'id': 1, 'name': '3DS Cheep Cheep Lagoon', '...",[],"[{'id': 87, 'name': '3DS Rainbow Road', 'debut...",True,...,False,False,False,False,False,False,False,True,False,False
2,3,Baby Daisy,Normal,Bubble,New York Tour,2019-09-25T00:00:00.000Z,"[{'id': 73, 'name': '3DS Daisy Hills R/T', 'de...",[],"[{'id': 108, 'name': 'SNES Choco Island 2R/T',...",True,...,False,False,False,False,False,False,False,True,False,False
3,4,Baby Rosalina,Normal,Bubble,Tokyo Tour,2019-10-09T00:00:00.000Z,"[{'id': 46, 'name': 'SNES Choco Island 2T', 'd...",[],"[{'id': 108, 'name': 'SNES Choco Island 2R/T',...",True,...,False,False,False,False,False,False,False,True,False,False
4,5,Baby Luigi,Normal,Boomerang Flower,Halloween Tour (2019),2019-10-23T00:00:00.000Z,"[{'id': 58, 'name': 'DS Luigi's Mansion R', 'd...",[],"[{'id': 112, 'name': 'DS Waluigi Pinball R/T',...",True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,Bowser (Santa),High-End,Coin Box,Winter Tour (2020),2020-12-02T00:00:00.000Z,"[{'id': 10, 'name': '3DS Shy Guy Bazaar', 'deb...","[{'id': 89, 'name': '3DS Rainbow Road T', 'deb...","[{'id': 103, 'name': '3DS Shy Guy Bazaar R/T',...",False,...,False,True,False,False,True,False,True,False,False,False
116,117,Lakitu (Party Time),High-End,Lucky Seven,New Year's 2021 Tour,2020-12-30T00:00:00.000Z,"[{'id': 88, 'name': '3DS Rainbow Road R', 'deb...","[{'id': 170, 'name': 'RMX Rainbow Road 1T', 'd...","[{'id': 41, 'name': 'N64 Kalimari Desert', 'de...",False,...,False,False,False,False,False,True,True,False,True,False
117,118,Birdo (Black),High-End,Bob-omb Cannon,Yoshi Tour (2021),2021-03-24T00:00:00.000Z,"[{'id': 163, 'name': 'DS Airship Fortress R', ...","[{'id': 61, 'name': 'DS Waluigi Pinball R', 'd...","[{'id': 22, 'name': 'GCN Yoshi Circuit', 'debu...",False,...,False,False,False,False,False,True,False,False,False,False
118,119,Shy Guy Ninja,High-End,Boomerang Flower,Ninja Tour,2021-04-07T00:00:00.000Z,"[{'id': 215, 'name': 'Ninja Hideaway', 'debut_...","[{'id': 39, 'name': '3DS Neo Bowser City R', '...","[{'id': 205, 'name': 'RMX Choco Island 2T', 'd...",False,...,False,False,False,False,False,False,False,False,False,False
119,120,King Bob-omb (Gold),High-End,Coin Box,Ninja Tour,2021-04-11T00:00:00.000Z,"[{'id': 217, 'name': 'Ninja Hideaway T', 'debu...","[{'id': 62, 'name': 'DS Waluigi Pinball T', 'd...","[{'id': 195, 'name': 'RMX Rainbow Road 2T', 'd...",False,...,False,False,False,False,True,False,False,False,False,False

In [19]:
#Check the datatypes
drivers_df.dtypes

position                         int64
name                            object
rarity                          object
special_skill                   object
debut_tour                      object
date_added                      object
level_one_favorite_courses      object
level_three_favorite_courses    object
level_six_favorite_courses      object
is_daily_select                   bool
is_in_pipes                       bool
baby                              bool
crown                             bool
dress                             bool
earrings                          bool
extended_tongue                   bool
gloves                            bool
hat                               bool
helmet                            bool
horns                             bool
kong                              bool
koopaling                         bool
mustache                          bool
ribbon                            bool
shell                             bool
short_sleeves                     bool
three_hairs                       bool
tie                               bool
dtype: object

In [20]:
#Cleaned Driver DF
cleaned_drivers_df = drivers_df.drop(['debut_tour','date_added','level_one_favorite_courses','level_three_favorite_courses','level_six_favorite_courses','is_daily_select',
                                      'is_in_pipes','baby','crown','dress','earrings','extended_tongue','gloves','helmet','horns','koopaling','mustache',
                                     'ribbon','shell','short_sleeves','three_hairs','tie','hat','kong'],axis=1)
cleaned_drivers_df

     position                 name    rarity     special_skill
0           1           Baby Mario    Normal  Boomerang Flower
1           2           Baby Peach    Normal            Bubble
2           3           Baby Daisy    Normal            Bubble
3           4        Baby Rosalina    Normal            Bubble
4           5           Baby Luigi    Normal  Boomerang Flower
..        ...                  ...       ...               ...
115       116       Bowser (Santa)  High-End          Coin Box
116       117  Lakitu (Party Time)  High-End       Lucky Seven
117       118        Birdo (Black)  High-End    Bob-omb Cannon
118       119        Shy Guy Ninja  High-End  Boomerang Flower
119       120  King Bob-omb (Gold)  High-End          Coin Box

[120 rows x 4 columns]

In [33]:
#export the cleaned_df to CSV
cleaned_drivers_df.to_csv("/Resources/drivers")