In [1]:
import requests
import pandas as pd

In [7]:
AllCourses = "https://mario-kart-tour-api.herokuapp.com/api/v1/courses/"

In [15]:
# Gather the course data
CourseData = requests.get(AllCourses).json()

In [ ]:
# LEVEL ONE TOP SHELF DRIVER CLEANING

In [29]:
# For each course, collect the level one top sheld driver IDs
level_1_top_shelf_driver = {}
for course in CourseData:
    value = []
    for driver in course["level_one_top_shelf_drivers"]:
        value.append(driver["id"])
    level_1_top_shelf_driver[course["name"]]=value
level_1_top_shelf_driver

{'3DS Cheep Cheep Lagoon': [2, 22, 35, 44, 78, 107],
 '3DS Cheep Cheep Lagoon R': [11, 19, 36, 79, 106, 107],
 '3DS Cheep Cheep Lagoon R/T': [6, 41, 54, 60, 70, 87, 111],
 '3DS Cheep Cheep Lagoon T': [16, 23, 31, 73, 79, 106],
 '3DS Daisy Hills': [19, 50, 70, 71, 80, 81, 107],
 '3DS Daisy Hills R': [21, 51, 57, 76, 80, 81, 86, 107],
 '3DS Daisy Hills R/T': [3, 25, 49, 69, 71, 81],
 '3DS Daisy Hills T': [3, 19, 54, 71, 87, 107],
 '3DS Mario Circuit': [],
 '3DS Mario Circuit R': [20, 22, 54, 61, 74, 75],
 '3DS Mario Circuit R/T': [48, 55, 62, 63, 68, 72, 78, 89],
 '3DS Mario Circuit T': [16, 24, 52, 66, 84, 103],
 '3DS Neo Bowser City': [27, 31, 42, 102, 106, 108],
 '3DS Neo Bowser City R': [33, 84, 101, 103, 109],
 '3DS Neo Bowser City R/T': [12, 59, 64, 85, 99, 105, 114],
 '3DS Neo Bowser City T': [31, 99, 102, 106, 108, 111, 119],
 '3DS Rainbow Road': [11, 39, 60, 66, 74, 88, 115],
 '3DS Rainbow Road R': [33, 59, 64, 66, 92, 108, 117],
 '3DS Rainbow Road R/T': [56, 64, 66, 92, 97, 103, 105],
 '3DS Rainbow Road T': [27, 37, 56, 64, 108, 114],
 '3DS Rock Rock Mountain': [18, 28, 33, 58, 80, 104],
 '3DS Rock Rock Mountain R': [29, 47, 60, 63, 106, 108],
 '3DS Rock Rock Mountain T': [20, 25, 41, 71, 100, 106],
 "3DS Rosalina's Ice World": [86, 88, 110, 112, 114, 117],
 "3DS Rosalina's Ice World R": [24, 64, 85, 91, 110],
 "3DS Rosalina's Ice World T": [53, 55, 63, 87, 90, 96, 108],
 '3DS Shy Guy Bazaar': [7, 34, 47, 53, 76, 89, 116],
 '3DS Shy Guy Bazaar R': [19, 43, 81, 99, 101, 114],
 '3DS Shy Guy Bazaar R/T': [33, 38, 44, 46, 59, 81, 87, 102, 119],
 '3DS Shy Guy Bazaar T': [8, 38, 57, 69, 100, 114],
 '3DS Toad Circuit': [20, 21, 40, 48, 71, 80, 110, 112],
 '3DS Toad Circuit R': [29, 54, 61, 76, 80, 93, 95],
 '3DS Toad Circuit R/T': [20, 57, 61, 73, 79],
 '3DS Toad Circuit T': [30, 36, 48, 61, 73, 79, 91, 93, 94],
 'Berlin Byways 2': [85, 89, 101, 112],
 'Berlin Byways 2R': [63, 66, 69, 101, 114, 117],
 'Berlin Byways 2R/T': [61, 69, 89, 102, 112, 113],
 'Berlin Byways 2T': [63, 76, 82, 87],
 'DS Airship Fortress': [78, 81, 85, 89, 90, 108, 111, 114, 120],
 'DS Airship Fortress R': [43, 88, 108, 111, 112, 118, 119],
 'DS Airship Fortress T': [40, 87, 88, 100, 109, 112, 114, 120],
 'DS DK Pass': [28, 55, 63, 106, 112],
 'DS DK Pass R': [22, 35, 63, 99, 104],
 'DS DK Pass R/T': [42, 53, 63, 64, 71, 104],
 'DS DK Pass T': [23, 32, 47, 56, 104, 112],
 "DS Luigi's Mansion": [23, 34, 53, 55, 75, 104, 115, 119],
 "DS Luigi's Mansion R": [5, 17, 49, 68, 84, 104, 112],
 "DS Luigi's Mansion R/T": [5, 34, 68, 69, 74, 101, 109],
 "DS Luigi's Mansion T": [23, 56, 84, 85, 100, 102, 108],
 'DS Waluigi Pinball': [1, 26, 33, 51, 59, 113, 117],
 'DS Waluigi Pinball R': [28, 50, 52, 81, 102, 108, 117],
 'DS Waluigi Pinball R/T': [23, 49, 56, 63, 97, 110, 112],
 'DS Waluigi Pinball T': [30, 48, 49, 87, 102, 108, 113, 116],
 "GBA Bowser's Castle 1": [12, 27, 79, 100, 105],
 "GBA Bowser's Castle 1R": [31, 43, 99, 105],
 "GBA Bowser's Castle 1R/T": [33, 40, 43, 99, 105, 111, 114],
 "GBA Bowser's Castle 1T": [8, 27, 52, 72, 112, 113],
 "GBA Bowser's Castle 2": [42, 43, 45, 99, 105, 112, 119],
 "GBA Bowser's Castle 2R": [27, 37, 43, 91, 99, 102, 116],
 "GBA Bowser's Castle 2R/T": [27, 31, 43, 47, 105, 108, 120],
 "GBA Bowser's Castle 2T": [37, 43, 105, 111, 112, 117],
 'GBA Sunset Wilds': [26, 68, 71, 86, 112, 114],
 'GBA Sunset Wilds R': [35, 67, 70, 74, 79],
 'GBA Sunset Wilds R/T': [57, 67, 80, 84, 86, 87, 90, 91],
 'GBA Sunset Wilds T': [71, 72, 76, 88, 118],
 'GCN Dino Dino Jungle': [28, 58, 91, 96, 99, 106, 108],
 'GCN Dino Dino Jungle R': [29, 45, 48, 86, 96, 103],
 'GCN Dino Dino Jungle R/T': [14, 25, 37, 45, 46, 70, 86, 96, 106],
 'GCN Dino Dino Jungle T': [27, 46, 73, 87, 99, 104, 108],
 'GCN Yoshi Circuit': [18, 25, 46, 58, 62, 70, 82, 88],
 'GCN Yoshi Circuit R': [17, 46, 50, 70, 71, 86, 102],
 'GCN Yoshi Circuit R/T': [18, 25, 56, 65, 69, 70, 77],
 'GCN Yoshi Circuit T': [18, 58, 62, 65, 73, 82, 91, 117],
 'London Loop': [36, 57, 68, 76, 107],
 'London Loop 2': [69],
 'London Loop 2R': [30, 65, 66, 69],
 'London Loop 2R/T': [38, 58, 59, 62, 69],
 'London Loop 2T': [102],
 'London Loop R': [30, 63, 69, 102],
 'London Loop R/T': [44, 57, 67, 72],
 'London Loop T': [25, 49, 67, 68, 83],
 'Los Angeles Laps': [59, 61, 78, 83],
 'Los Angeles Laps R': [32, 76, 78, 113],
 'Los Angeles Laps R/T': [72, 106, 110, 111],
 'Los Angeles Laps T': [33, 72, 77, 113],
 'Merry Mountain': [63, 68, 79, 85, 89, 90, 116],
 'Merry Mountain R': [30, 55, 57, 91, 115],
 'Merry Mountain T': [58, 73, 84, 109, 117],
 'N64 Choco Mountain': [56, 75, 79, 89, 104, 112, 113],
 'N64 Choco Mountain R': [66, 75, 79, 89, 99, 106, 113],
 'N64 Choco Mountain T': [66, 71, 80, 86, 101, 110, 120],
 'N64 Frappe Snowland': [38, 42, 62, 69, 85, 110, 116],
 'N64 Frappe Snowland R': [42, 47, 59, 66, 69, 77],
 'N64 Frappe Snowland R/T': [37, 62, 64, 65, 96, 110, 113],
 'N64 Frappe Snowland T': [39, 42, 62, 63, 66],
 'N64 Kalimari Desert': [12, 13, 40, 86, 101],
 'N64 Kalimari Desert 2': [59, 83, 86, 89, 90, 105, 109, 111],
 'N64 Kalimari Desert 2R': [56, 80, 88, 107, 110, 115, 120],
 'N64 Kalimari Desert 2T': [44, 79, 86, 109, 110, 115, 120],
 'N64 Kalimari Desert R': [10, 32, 80, 89, 104, 108],
 'N64 Kalimari Desert R/T': [10, 12, 31, 40, 44, 80, 86],
 'N64 Kalimari Desert T': [14, 32, 38, 72, 86, 117],
 'N64 Koopa Troopa Beach': [6, 16, 46, 54, 77, 83, 103],
 'N64 Koopa Troopa Beach R': [17, 57, 61, 101, 103],
 'N64 Koopa Troopa Beach R/T': [36, 54, 58, 77, 81, 87, 103],
 'N64 Koopa Troopa Beach T': [17, 54, 60, 80, 83, 101],
 'N64 Royal Raceway': [48, 59, 76, 80, 85, 116],
 'N64 Royal Raceway R': [51, 54, 76, 77, 80, 107, 113],
 'N64 Royal Raceway R/T': [73, 85, 90, 94, 95],
 'N64 Royal Raceway T': [56, 62, 77, 82, 85, 86],
 'New York Minute': [49],
 'New York Minute 2': [49, 58],
 'New York Minute 2R': [49, 59],
 'New York Minute 2R/T': [29, 50, 59],
 'New York Minute 2T': [58, 59],
 'New York Minute 3': [49, 59, 82, 102, 105],
 'New York Minute 3R': [23, 28, 50, 101, 102, 106],
 'New York Minute 3R/T': [50, 52, 73, 101],
 'New York Minute 3T': [22, 49, 53, 73, 83, 99],
 'New York Minute R': [50],
 'New York Minute R/T': [49],
 'New York Minute T': [50],
 'Ninja Hideaway': [119],
 'Ninja Hideaway R': [119],
 'Ninja Hideaway T': [120],
 'Paris Promenade': [54, 55, 68, 102],
 'Paris Promenade 2': [65, 69, 71, 75, 111],
 'Paris Promenade 2R': [5, 40, 54, 91, 106, 117],
 'Paris Promenade 2R/T': [36, 50, 51, 65],
 'Paris Promenade 2T': [38, 85, 87, 106, 117],
 'Paris Promenade R': [38, 44, 55, 62, 101, 103],
 'Paris Promenade R/T': [22, 54, 103],
 'Paris Promenade T': [30, 31, 83, 101, 104],
 'RMX Choco Island 1': [44, 56, 69, 74, 75, 110, 115],
 'RMX Choco Island 1R': [62, 63, 65, 72, 75, 78, 79, 107],
 'RMX Choco Island 1R/T': [97],
 'RMX Choco Island 1T': [18, 19, 45, 57, 83, 107],
 'RMX Choco Island 2': [74, 76, 79, 90, 96, 109, 120],
 'RMX Choco Island 2R': [56, 69, 100, 101, 103, 106, 120],
 'RMX Choco Island 2T': [65, 76, 89, 92, 93, 117, 119],
 'RMX Mario Circuit 1': [26, 47, 67, 75, 76, 78, 95],
 'RMX Mario Circuit 1R': [41, 63, 66, 67, 70, 78],
 'RMX Mario Circuit 1R/T': [23, 52, 67, 70, 71, 76, 83, 84, 94],
 'RMX Mario Circuit 1T': [41, 67, 69, 72, 74, 83, 87, 101],
 'RMX Rainbow Road 1': [60, 66, 77, 82, 88, 90, 92],
 'RMX Rainbow Road 1R': [47, 58, 81, 82, 92, 105, 108, 117],
 'RMX Rainbow Road 1R/T': [63, 73, 87, 88, 90, 91, 116],
 'RMX Rainbow Road 1T': [50, 58, 63, 73, 81, 83, 90, 111, 113],
 'RMX Rainbow Road 2': [76, 85, 90, 92, 116, 117],
 'RMX Rainbow Road 2R': [16, 22, 51, 59, 66, 88, 100, 120],
 'RMX Rainbow Road 2T': [65, 82, 83, 84, 92, 93],
 'SNES Choco Island 1': [49, 75, 77, 105, 110],
 'SNES Choco Island 1R': [48, 65, 101, 103, 113],
 'SNES Choco Island 1T': [37, 65, 77, 87, 92, 108, 110],
 'SNES Choco Island 2': [15, 53, 65, 74, 75, 110, 115],
 'SNES Choco Island 2R': [9, 31, 74, 75, 83, 110],
 'SNES Choco Island 2R/T': [37, 61, 72, 73, 74, 120],
 'SNES Choco Island 2T': [4, 32, 62, 80, 82, 83],
 'SNES Donut Plains 1': [41, 45, 75, 76, 107, 109],
 'SNES Donut Plains 1R': [20, 45, 50, 51, 65, 76, 109],
 'SNES Donut Plains 1R/T': [48, 51, 68, 71, 75, 81, 97, 109],
 'SNES Donut Plains 1T': [36, 40, 77, 103, 107],
 'SNES Donut Plains 2': [65, 86, 90, 112, 120],
 'SNES Donut Plains 2R': [37, 64, 65, 71, 89, 91, 92],
 'SNES Donut Plains 2R/T': [57, 65, 92, 93, 118],
 'SNES Donut Plains 2T': [63, 83, 92, 117, 119],
 'SNES Ghost Valley 1': [23, 38, 53, 85, 88, 100],
 'SNES Ghost Valley 1R': [34, 39, 71, 86, 100, 116],
 'SNES Ghost Valley 1R/T': [34, 35, 81, 82, 102, 105, 111, 119],
 'SNES Ghost Valley 1T': [30, 35, 53, 71, 73, 115],
 'SNES Koopa Troopa Beach 2': [45, 63, 77, 79, 105, 120],
 'SNES Koopa Troopa Beach 2R': [25, 32, 36, 46, 78, 115],
 'SNES Koopa Troopa Beach 2T': [64, 71, 72, 78, 81, 112],
 'SNES Mario Circuit 1': [16, 24, 36, 48, 52, 60, 65, 67, 84, 110],
 'SNES Mario Circuit 1R': [35, 54, 55, 78, 84, 94],
 'SNES Mario Circuit 1R/T': [20, 36, 55, 64, 72, 82, 94, 103],
 'SNES Mario Circuit 1T': [1, 17, 45, 52, 72, 89],
 'SNES Mario Circuit 2': [24, 52, 60, 67, 70],
 'SNES Mario Circuit 2R': [47, 51, 60, 68, 70],
 'SNES Mario Circuit 2R/T': [39, 61, 63, 64, 65, 67, 103],
 'SNES Mario Circuit 2T': [11, 24, 30, 67, 68, 78, 85],
 'SNES Mario Circuit 3': [24, 50, 54, 78, 84, 113],
 'SNES Mario Circuit 3R': [21, 40, 52, 57, 79, 117],
 'SNES Mario Circuit 3R/T': [16, 17, 40, 61, 75, 87],
 'SNES Mario Circuit 3T': [30, 39, 51, 60, 68, 117],
 'SNES Rainbow Road': [22, 47, 59, 64, 76],
 'SNES Rainbow Road R': [11, 55, 64, 65, 76, 105],
 'SNES Rainbow Road R/T': [22, 53, 56, 77, 82, 85, 100, 114, 115],
 'SNES Rainbow Road T': [4, 47, 55, 56, 82],
 'SNES Vanilla Lake 1': [11, 63, 64, 74, 107, 116],
 'SNES Vanilla Lake 1R': [42, 64, 74, 104, 111, 116],
 'SNES Vanilla Lake 1R/T': [42, 66, 73, 74, 78, 97, 105, 120],
 'SNES Vanilla Lake 1T': [31, 55, 58, 62, 93, 106, 111, 115],
 'Sydney Sprint': [96],
 'Sydney Sprint R': [],
 'Sydney Sprint R/T': [46, 96],
 'Sydney Sprint T': [120],
 'Tokyo Blur': [24, 52, 61, 81, 111],
 'Tokyo Blur 2': [38, 60, 69, 110],
 'Tokyo Blur 2R': [34, 60, 61, 110],
 'Tokyo Blur 2R/T': [25, 53, 101, 103],
 'Tokyo Blur 2T': [25, 69, 103],
 'Tokyo Blur 3': [58, 60, 75, 81],
 'Tokyo Blur 3R': [30, 52, 58, 71, 81],
 'Tokyo Blur 3T': [51, 52, 57, 71, 73, 109],
 'Tokyo Blur 4': [26, 81, 91, 94, 95, 110],
 'Tokyo Blur 4R': [47, 62, 93, 115, 117, 118],
 'Tokyo Blur 4R/T': [72, 82, 90, 92],
 'Tokyo Blur 4T': [60, 67, 73, 87, 92, 106, 118],
 'Tokyo Blur R': [51, 60, 69, 70, 111, 113, 114],
 'Tokyo Blur R/T': [52, 72, 82, 83],
 'Tokyo Blur T': [51, 69, 70, 74, 109, 113, 114],
 'Vancouver Velocity': [39, 42, 66, 105],
 'Vancouver Velocity R': [42, 66, 104, 108, 114],
 'Vancouver Velocity R/T': [39, 58, 66],
 'Vancouver Velocity T': [37, 64, 69, 73, 83],
 'Wii DK Summit': [80, 86, 93, 112, 113],
 'Wii DK Summit R': [71, 75, 79, 84, 113, 119],
 'Wii DK Summit T': [73, 89, 94, 96, 104, 110, 114, 119],
 'Wii Maple Treeway': [61, 74, 84, 90, 92, 107, 116],
 'Wii Maple Treeway R': [25, 46, 53, 54, 86, 114, 115],
 'Wii Maple Treeway T': [68, 70, 85, 87, 88, 114, 116]}

In [38]:
# Create a dataframe
level_one_df = pd.DataFrame.from_dict(level_1_top_shelf_driver, orient='index')
level_one_df

,0,1,2,3,4,5,6,7,8,9
3DS Cheep Cheep Lagoon,2.0,22.0,35.0,44.0,78.0,107.0,NaN,NaN,NaN,NaN
3DS Cheep Cheep Lagoon R,11.0,19.0,36.0,79.0,106.0,107.0,NaN,NaN,NaN,NaN
3DS Cheep Cheep Lagoon R/T,6.0,41.0,54.0,60.0,70.0,87.0,111.0,NaN,NaN,NaN
3DS Cheep Cheep Lagoon T,16.0,23.0,31.0,73.0,79.0,106.0,NaN,NaN,NaN,NaN
3DS Daisy Hills,19.0,50.0,70.0,71.0,80.0,81.0,107.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
Wii DK Summit R,71.0,75.0,79.0,84.0,113.0,119.0,NaN,NaN,NaN,NaN
Wii DK Summit T,73.0,89.0,94.0,96.0,104.0,110.0,114.0,119.0,NaN,NaN
Wii Maple Treeway,61.0,74.0,84.0,90.0,92.0,107.0,116.0,NaN,NaN,NaN
Wii Maple Treeway R,25.0,46.0,53.0,54.0,86.0,114.0,115.0,NaN,NaN,NaN
Wii Maple Treeway T,68.0,70.0,85.0,87.0,88.0,114.0,116.0,NaN,NaN,NaN

In [ ]:
# Create a dataframe
level_one_df = pd.DataFrame.from_dict(level_1_top_shelf_driver, orient='index')
level_one_df

In [55]:
# Make dataframe prettier
level_one_df = level_one_df.rename_axis("course_name")
level_one_df = level_one_df.rename(columns={0:"driver_id_1",1:"driver_id_2",2:"driver_id_3",3:"driver_id_4",4:"driver_id_5",5:"driver_id_6",6:"driver_id_7",7:"driver_id_8",8:"driver_id_9",9:"driver_id_10"})
level_one_df

,driver_id_1,driver_id_2,driver_id_3,driver_id_4,driver_id_5,driver_id_6,driver_id_7,driver_id_8,driver_id_9,driver_id_10
course_name,,,,,,,,,,
3DS Cheep Cheep Lagoon,2.0,22.0,35.0,44.0,78.0,107.0,NaN,NaN,NaN,NaN
3DS Cheep Cheep Lagoon R,11.0,19.0,36.0,79.0,106.0,107.0,NaN,NaN,NaN,NaN
3DS Cheep Cheep Lagoon R/T,6.0,41.0,54.0,60.0,70.0,87.0,111.0,NaN,NaN,NaN
3DS Cheep Cheep Lagoon T,16.0,23.0,31.0,73.0,79.0,106.0,NaN,NaN,NaN,NaN
3DS Daisy Hills,19.0,50.0,70.0,71.0,80.0,81.0,107.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
Wii DK Summit R,71.0,75.0,79.0,84.0,113.0,119.0,NaN,NaN,NaN,NaN
Wii DK Summit T,73.0,89.0,94.0,96.0,104.0,110.0,114.0,119.0,NaN,NaN
Wii Maple Treeway,61.0,74.0,84.0,90.0,92.0,107.0,116.0,NaN,NaN,NaN
Wii Maple Treeway R,25.0,46.0,53.0,54.0,86.0,114.0,115.0,NaN,NaN,NaN
Wii Maple Treeway T,68.0,70.0,85.0,87.0,88.0,114.0,116.0,NaN,NaN,NaN

In [57]:
# Count NaN values per column
level_one_df.isna().sum()

driver_id_1       2
driver_id_2      14
driver_id_3      18
driver_id_4      22
driver_id_5      42
driver_id_6      78
driver_id_7     138
driver_id_8     194
driver_id_9     214
driver_id_10    221
dtype: int64

In [83]:
# Drop rows with NaN in driver_id_1,2,3,4,5 and check that they were dropped
level_one_df = level_one_df.dropna(subset=["driver_id_1","driver_id_2","driver_id_3","driver_id_4","driver_id_5"])
level_one_df.isna().sum()

driver_id_1       0
driver_id_2       0
driver_id_3       0
driver_id_4       0
driver_id_5       0
driver_id_6      36
driver_id_7      96
driver_id_8     152
driver_id_9     172
driver_id_10    179
dtype: int64

In [86]:
# Drop remaining columnds with NaN values
level_one_df = level_one_df.drop(columns=["driver_id_6","driver_id_7","driver_id_8","driver_id_9","driver_id_10"])
level_one_df

,driver_id_1,driver_id_2,driver_id_3,driver_id_4,driver_id_5
course_name,,,,,
3DS Cheep Cheep Lagoon,2.0,22.0,35.0,44.0,78.0
3DS Cheep Cheep Lagoon R,11.0,19.0,36.0,79.0,106.0
3DS Cheep Cheep Lagoon R/T,6.0,41.0,54.0,60.0,70.0
3DS Cheep Cheep Lagoon T,16.0,23.0,31.0,73.0,79.0
3DS Daisy Hills,19.0,50.0,70.0,71.0,80.0
...,...,...,...,...,...
Wii DK Summit R,71.0,75.0,79.0,84.0,113.0
Wii DK Summit T,73.0,89.0,94.0,96.0,104.0
Wii Maple Treeway,61.0,74.0,84.0,90.0,92.0
Wii Maple Treeway R,25.0,46.0,53.0,54.0,86.0
Wii Maple Treeway T,68.0,70.0,85.0,87.0,88.0

In [ ]:
# LEVEL THREE TOP SHELF DRIVER CLEANING

In [77]:
# For each course, collect the level three top sheld driver IDs
level_3_top_shelf_driver = {}
for course in CourseData:
    value = []
    for driver in course["level_three_top_shelf_drivers"]:
        value.append(driver["id"])
    level_3_top_shelf_driver[course["name"]]=value
level_3_top_shelf_driver

{'3DS Cheep Cheep Lagoon': [],
 '3DS Cheep Cheep Lagoon R': [54, 78],
 '3DS Cheep Cheep Lagoon R/T': [38, 79],
 '3DS Cheep Cheep Lagoon T': [],
 '3DS Daisy Hills': [69, 76],
 '3DS Daisy Hills R': [71, 74],
 '3DS Daisy Hills R/T': [72, 97],
 '3DS Daisy Hills T': [57, 72],
 '3DS Mario Circuit': [],
 '3DS Mario Circuit R': [51],
 '3DS Mario Circuit R/T': [64, 77],
 '3DS Mario Circuit T': [102],
 '3DS Neo Bowser City': [53, 111],
 '3DS Neo Bowser City R': [119],
 '3DS Neo Bowser City R/T': [29, 49, 50],
 '3DS Neo Bowser City T': [],
 '3DS Rainbow Road': [77],
 '3DS Rainbow Road R': [114],
 '3DS Rainbow Road R/T': [63, 80, 85],
 '3DS Rainbow Road T': [48, 116],
 '3DS Rock Rock Mountain': [60],
 '3DS Rock Rock Mountain R': [],
 '3DS Rock Rock Mountain T': [],
 "3DS Rosalina's Ice World": [],
 "3DS Rosalina's Ice World R": [88],
 "3DS Rosalina's Ice World T": [],
 '3DS Shy Guy Bazaar': [81],
 '3DS Shy Guy Bazaar R': [91],
 '3DS Shy Guy Bazaar R/T': [19, 73],
 '3DS Shy Guy Bazaar T': [58],
 '3DS Toad Circuit': [47, 76],
 '3DS Toad Circuit R': [94],
 '3DS Toad Circuit R/T': [21, 103],
 '3DS Toad Circuit T': [110, 112],
 'Berlin Byways 2': [],
 'Berlin Byways 2R': [],
 'Berlin Byways 2R/T': [],
 'Berlin Byways 2T': [],
 'DS Airship Fortress': [115],
 'DS Airship Fortress R': [115],
 'DS Airship Fortress T': [89],
 'DS DK Pass': [],
 'DS DK Pass R': [59],
 'DS DK Pass R/T': [55, 61, 99],
 'DS DK Pass T': [65],
 "DS Luigi's Mansion": [],
 "DS Luigi's Mansion R": [63, 100],
 "DS Luigi's Mansion R/T": [23, 32, 35],
 "DS Luigi's Mansion T": [109, 110],
 'DS Waluigi Pinball': [52, 108],
 'DS Waluigi Pinball R': [33, 118],
 'DS Waluigi Pinball R/T': [106],
 'DS Waluigi Pinball T': [89, 120],
 "GBA Bowser's Castle 1": [104],
 "GBA Bowser's Castle 1R": [79],
 "GBA Bowser's Castle 1R/T": [59],
 "GBA Bowser's Castle 1T": [31],
 "GBA Bowser's Castle 2": [100],
 "GBA Bowser's Castle 2R": [105],
 "GBA Bowser's Castle 2R/T": [30],
 "GBA Bowser's Castle 2T": [99, 106],
 'GBA Sunset Wilds': [],
 'GBA Sunset Wilds R': [118],
 'GBA Sunset Wilds R/T': [97],
 'GBA Sunset Wilds T': [],
 'GCN Dino Dino Jungle': [80, 109],
 'GCN Dino Dino Jungle R': [],
 'GCN Dino Dino Jungle R/T': [40, 58, 116],
 'GCN Dino Dino Jungle T': [43, 70, 86],
 'GCN Yoshi Circuit': [71],
 'GCN Yoshi Circuit R': [82],
 'GCN Yoshi Circuit R/T': [16, 54, 87],
 'GCN Yoshi Circuit T': [26, 48, 95],
 'London Loop': [],
 'London Loop 2': [],
 'London Loop 2R': [],
 'London Loop 2R/T': [],
 'London Loop 2T': [],
 'London Loop R': [],
 'London Loop R/T': [],
 'London Loop T': [],
 'Los Angeles Laps': [],
 'Los Angeles Laps R': [],
 'Los Angeles Laps R/T': [],
 'Los Angeles Laps T': [],
 'Merry Mountain': [88],
 'Merry Mountain R': [],
 'Merry Mountain T': [],
 'N64 Choco Mountain': [],
 'N64 Choco Mountain R': [119],
 'N64 Choco Mountain T': [83],
 'N64 Frappe Snowland': [66, 84],
 'N64 Frappe Snowland R': [68],
 'N64 Frappe Snowland R/T': [17, 18, 66],
 'N64 Frappe Snowland T': [93],
 'N64 Kalimari Desert': [84],
 'N64 Kalimari Desert 2': [],
 'N64 Kalimari Desert 2R': [86],
 'N64 Kalimari Desert 2T': [83],
 'N64 Kalimari Desert R': [],
 'N64 Kalimari Desert R/T': [27, 101],
 'N64 Kalimari Desert T': [41, 108],
 'N64 Koopa Troopa Beach': [],
 'N64 Koopa Troopa Beach R': [96],
 'N64 Koopa Troopa Beach R/T': [39, 45, 74],
 'N64 Koopa Troopa Beach T': [42, 103],
 'N64 Royal Raceway': [107],
 'N64 Royal Raceway R': [90],
 'N64 Royal Raceway R/T': [],
 'N64 Royal Raceway T': [],
 'New York Minute': [],
 'New York Minute 2': [],
 'New York Minute 2R': [],
 'New York Minute 2R/T': [],
 'New York Minute 2T': [],
 'New York Minute 3': [],
 'New York Minute 3R': [],
 'New York Minute 3R/T': [],
 'New York Minute 3T': [],
 'New York Minute R': [],
 'New York Minute R/T': [],
 'New York Minute T': [],
 'Ninja Hideaway': [],
 'Ninja Hideaway R': [],
 'Ninja Hideaway T': [],
 'Paris Promenade': [],
 'Paris Promenade 2': [91],
 'Paris Promenade 2R': [],
 'Paris Promenade 2R/T': [],
 'Paris Promenade 2T': [],
 'Paris Promenade R': [],
 'Paris Promenade R/T': [],
 'Paris Promenade T': [],
 'RMX Choco Island 1': [92],
 'RMX Choco Island 1R': [114],
 'RMX Choco Island 1R/T': [],
 'RMX Choco Island 1T': [62, 73],
 'RMX Choco Island 2': [],
 'RMX Choco Island 2R': [],
 'RMX Choco Island 2T': [96],
 'RMX Mario Circuit 1': [],
 'RMX Mario Circuit 1R': [95],
 'RMX Mario Circuit 1R/T': [69],
 'RMX Mario Circuit 1T': [94],
 'RMX Rainbow Road 1': [],
 'RMX Rainbow Road 1R': [],
 'RMX Rainbow Road 1R/T': [],
 'RMX Rainbow Road 1T': [117],
 'RMX Rainbow Road 2': [],
 'RMX Rainbow Road 2R': [117],
 'RMX Rainbow Road 2T': [],
 'SNES Choco Island 1': [],
 'SNES Choco Island 1R': [],
 'SNES Choco Island 1T': [],
 'SNES Choco Island 2': [],
 'SNES Choco Island 2R': [57, 62, 101],
 'SNES Choco Island 2R/T': [107],
 'SNES Choco Island 2T': [34, 44],
 'SNES Donut Plains 1': [113],
 'SNES Donut Plains 1R': [25, 113],
 'SNES Donut Plains 1R/T': [],
 'SNES Donut Plains 1T': [75],
 'SNES Donut Plains 2': [],
 'SNES Donut Plains 2R': [120],
 'SNES Donut Plains 2R/T': [],
 'SNES Donut Plains 2T': [],
 'SNES Ghost Valley 1': [],
 'SNES Ghost Valley 1R': [112],
 'SNES Ghost Valley 1R/T': [37, 60],
 'SNES Ghost Valley 1T': [],
 'SNES Koopa Troopa Beach 2': [],
 'SNES Koopa Troopa Beach 2R': [64, 81, 111],
 'SNES Koopa Troopa Beach 2T': [46],
 'SNES Mario Circuit 1': [51, 56, 82],
 'SNES Mario Circuit 1R': [],
 'SNES Mario Circuit 1R/T': [61, 102],
 'SNES Mario Circuit 1T': [20, 68, 78],
 'SNES Mario Circuit 2': [75],
 'SNES Mario Circuit 2R': [67],
 'SNES Mario Circuit 2R/T': [],
 'SNES Mario Circuit 2T': [70],
 'SNES Mario Circuit 3': [],
 'SNES Mario Circuit 3R': [50, 55],
 'SNES Mario Circuit 3R/T': [24, 36],
 'SNES Mario Circuit 3T': [56],
 'SNES Rainbow Road': [105],
 'SNES Rainbow Road R': [22, 47],
 'SNES Rainbow Road R/T': [49, 65],
 'SNES Rainbow Road T': [52, 53],
 'SNES Vanilla Lake 1': [67, 104],
 'SNES Vanilla Lake 1R': [93],
 'SNES Vanilla Lake 1R/T': [28, 87],
 'SNES Vanilla Lake 1T': [],
 'Sydney Sprint': [],
 'Sydney Sprint R': [],
 'Sydney Sprint R/T': [],
 'Sydney Sprint T': [],
 'Tokyo Blur': [],
 'Tokyo Blur 2': [],
 'Tokyo Blur 2R': [],
 'Tokyo Blur 2R/T': [],
 'Tokyo Blur 2T': [],
 'Tokyo Blur 3': [],
 'Tokyo Blur 3R': [],
 'Tokyo Blur 3T': [],
 'Tokyo Blur 4': [],
 'Tokyo Blur 4R': [],
 'Tokyo Blur 4R/T': [],
 'Tokyo Blur 4T': [],
 'Tokyo Blur R': [],
 'Tokyo Blur R/T': [],
 'Tokyo Blur T': [],
 'Vancouver Velocity': [],
 'Vancouver Velocity R': [],
 'Vancouver Velocity R/T': [],
 'Vancouver Velocity T': [],
 'Wii DK Summit': [],
 'Wii DK Summit R': [],
 'Wii DK Summit T': [],
 'Wii Maple Treeway': [],
 'Wii Maple Treeway R': [85, 92],
 'Wii Maple Treeway T': [90]}

In [78]:
# Create a dataframe
level_three_df = pd.DataFrame.from_dict(level_3_top_shelf_driver, orient='index')
level_three_df

                               0     1   2
3DS Cheep Cheep Lagoon       NaN   NaN NaN
3DS Cheep Cheep Lagoon R    54.0  78.0 NaN
3DS Cheep Cheep Lagoon R/T  38.0  79.0 NaN
3DS Cheep Cheep Lagoon T     NaN   NaN NaN
3DS Daisy Hills             69.0  76.0 NaN
...                          ...   ...  ..
Wii DK Summit R              NaN   NaN NaN
Wii DK Summit T              NaN   NaN NaN
Wii Maple Treeway            NaN   NaN NaN
Wii Maple Treeway R         85.0  92.0 NaN
Wii Maple Treeway T         90.0   NaN NaN

[222 rows x 3 columns]

In [79]:
# Make dataframe prettier
level_three_df = level_three_df.rename_axis("course_name")
level_three_df = level_three_df.rename(columns={0:"driver_id_1",1:"driver_id_2",2:"driver_id_3"})
level_three_df

                            driver_id_1  driver_id_2  driver_id_3
course_name
3DS Cheep Cheep Lagoon              NaN          NaN          NaN
3DS Cheep Cheep Lagoon R           54.0         78.0          NaN
3DS Cheep Cheep Lagoon R/T         38.0         79.0          NaN
3DS Cheep Cheep Lagoon T            NaN          NaN          NaN
3DS Daisy Hills                    69.0         76.0          NaN
...                                 ...          ...          ...
Wii DK Summit R                     NaN          NaN          NaN
Wii DK Summit T                     NaN          NaN          NaN
Wii Maple Treeway                   NaN          NaN          NaN
Wii Maple Treeway R                85.0         92.0          NaN
Wii Maple Treeway T                90.0          NaN          NaN

[222 rows x 3 columns]

In [80]:
# Count NaN values per column
level_three_df.isna().sum()

driver_id_1    110
driver_id_2    171
driver_id_3    208
dtype: int64

In [81]:
# Drop rows with NaN in driver_id_1 and check that they were dropped
level_three_df = level_three_df.dropna(subset=["driver_id_1"])
level_three_df.isna().sum()

driver_id_1     0
driver_id_2    61
driver_id_3    98
dtype: int64

In [87]:
# Drop remaining columnds with NaN values
level_three_df = level_three_df.drop(columns=["driver_id_2","driver_id_3"])
level_three_df

                            driver_id_1
course_name
3DS Cheep Cheep Lagoon R           54.0
3DS Cheep Cheep Lagoon R/T         38.0
3DS Daisy Hills                    69.0
3DS Daisy Hills R                  71.0
3DS Daisy Hills R/T                72.0
...                                 ...
SNES Vanilla Lake 1                67.0
SNES Vanilla Lake 1R               93.0
SNES Vanilla Lake 1R/T             28.0
Wii Maple Treeway R                85.0
Wii Maple Treeway T                90.0

[112 rows x 1 columns]

In [ ]:
# LEVEL SIX TOP SHELF DRIVER CLEANING

In [31]:
level_6_top_shelf_driver = {}
for course in CourseData:
    value = []
    for driver in course["level_six_top_shelf_drivers"]:
        value.append(driver["id"])
    level_6_top_shelf_driver[course["name"]]=value
level_6_top_shelf_driver

{'3DS Cheep Cheep Lagoon': [60, 106],
 '3DS Cheep Cheep Lagoon R': [],
 '3DS Cheep Cheep Lagoon R/T': [10, 83],
 '3DS Cheep Cheep Lagoon T': [70, 103],
 '3DS Daisy Hills': [],
 '3DS Daisy Hills R': [],
 '3DS Daisy Hills R/T': [7],
 '3DS Daisy Hills T': [],
 '3DS Mario Circuit': [],
 '3DS Mario Circuit R': [17],
 '3DS Mario Circuit R/T': [],
 '3DS Mario Circuit T': [6, 21],
 '3DS Neo Bowser City': [],
 '3DS Neo Bowser City R': [108],
 '3DS Neo Bowser City R/T': [],
 '3DS Neo Bowser City T': [50],
 '3DS Rainbow Road': [2],
 '3DS Rainbow Road R': [54],
 '3DS Rainbow Road R/T': [84],
 '3DS Rainbow Road T': [11],
 '3DS Rock Rock Mountain': [63],
 '3DS Rock Rock Mountain R': [100],
 '3DS Rock Rock Mountain T': [99, 101],
 "3DS Rosalina's Ice World": [93],
 "3DS Rosalina's Ice World R": [117],
 "3DS Rosalina's Ice World T": [],
 '3DS Shy Guy Bazaar': [114],
 '3DS Shy Guy Bazaar R': [49, 76],
 '3DS Shy Guy Bazaar R/T': [116],
 '3DS Shy Guy Bazaar T': [19],
 '3DS Toad Circuit': [95],
 '3DS Toad Circuit R': [45, 68],
 '3DS Toad Circuit R/T': [],
 '3DS Toad Circuit T': [72],
 'Berlin Byways 2': [],
 'Berlin Byways 2R': [],
 'Berlin Byways 2R/T': [],
 'Berlin Byways 2T': [],
 'DS Airship Fortress': [79, 118],
 'DS Airship Fortress R': [78, 109],
 'DS Airship Fortress T': [78, 110],
 'DS DK Pass': [66, 104],
 'DS DK Pass R': [55],
 'DS DK Pass R/T': [],
 'DS DK Pass T': [100],
 "DS Luigi's Mansion": [48, 50, 102],
 "DS Luigi's Mansion R": [57, 85],
 "DS Luigi's Mansion R/T": [87],
 "DS Luigi's Mansion T": [69],
 'DS Waluigi Pinball': [47, 89],
 'DS Waluigi Pinball R': [23, 113],
 'DS Waluigi Pinball R/T': [5, 44],
 'DS Waluigi Pinball T': [37, 73],
 "GBA Bowser's Castle 1": [8],
 "GBA Bowser's Castle 1R": [27],
 "GBA Bowser's Castle 1R/T": [14],
 "GBA Bowser's Castle 1T": [9],
 "GBA Bowser's Castle 2": [34, 88],
 "GBA Bowser's Castle 2R": [15],
 "GBA Bowser's Castle 2R/T": [32],
 "GBA Bowser's Castle 2T": [],
 'GBA Sunset Wilds': [],
 'GBA Sunset Wilds R': [],
 'GBA Sunset Wilds R/T': [],
 'GBA Sunset Wilds T': [26, 86],
 'GCN Dino Dino Jungle': [86, 103],
 'GCN Dino Dino Jungle R': [18],
 'GCN Dino Dino Jungle R/T': [13],
 'GCN Dino Dino Jungle T': [],
 'GCN Yoshi Circuit': [118],
 'GCN Yoshi Circuit R': [74],
 'GCN Yoshi Circuit R/T': [12],
 'GCN Yoshi Circuit T': [36],
 'London Loop': [],
 'London Loop 2': [],
 'London Loop 2R': [],
 'London Loop 2R/T': [],
 'London Loop 2T': [],
 'London Loop R': [],
 'London Loop R/T': [],
 'London Loop T': [],
 'Los Angeles Laps': [],
 'Los Angeles Laps R': [],
 'Los Angeles Laps R/T': [],
 'Los Angeles Laps T': [],
 'Merry Mountain': [91],
 'Merry Mountain R': [116],
 'Merry Mountain T': [90],
 'N64 Choco Mountain': [71, 101, 110],
 'N64 Choco Mountain R': [80, 112],
 'N64 Choco Mountain T': [77],
 'N64 Frappe Snowland': [58],
 'N64 Frappe Snowland R': [58, 85],
 'N64 Frappe Snowland R/T': [],
 'N64 Frappe Snowland T': [53, 65, 111],
 'N64 Kalimari Desert': [33, 117],
 'N64 Kalimari Desert 2': [79, 80, 107],
 'N64 Kalimari Desert 2R': [59, 105, 109],
 'N64 Kalimari Desert 2T': [61],
 'N64 Kalimari Desert R': [41, 81, 102],
 'N64 Kalimari Desert R/T': [],
 'N64 Kalimari Desert T': [],
 'N64 Koopa Troopa Beach': [20, 40],
 'N64 Koopa Troopa Beach R': [16, 29],
 'N64 Koopa Troopa Beach R/T': [],
 'N64 Koopa Troopa Beach T': [96],
 'N64 Royal Raceway': [51, 56],
 'N64 Royal Raceway R': [56, 60],
 'N64 Royal Raceway R/T': [],
 'N64 Royal Raceway T': [59, 106],
 'New York Minute': [],
 'New York Minute 2': [],
 'New York Minute 2R': [],
 'New York Minute 2R/T': [],
 'New York Minute 2T': [],
 'New York Minute 3': [],
 'New York Minute 3R': [],
 'New York Minute 3R/T': [],
 'New York Minute 3T': [],
 'New York Minute R': [],
 'New York Minute R/T': [],
 'New York Minute T': [],
 'Ninja Hideaway': [120],
 'Ninja Hideaway R': [46],
 'Ninja Hideaway T': [119],
 'Paris Promenade': [],
 'Paris Promenade 2': [],
 'Paris Promenade 2R': [],
 'Paris Promenade 2R/T': [],
 'Paris Promenade 2T': [],
 'Paris Promenade R': [],
 'Paris Promenade R/T': [],
 'Paris Promenade T': [],
 'RMX Choco Island 1': [62, 65, 73, 107],
 'RMX Choco Island 1R': [49, 69, 74, 112],
 'RMX Choco Island 1R/T': [],
 'RMX Choco Island 1T': [72, 75],
 'RMX Choco Island 2': [92],
 'RMX Choco Island 2R': [],
 'RMX Choco Island 2T': [119],
 'RMX Mario Circuit 1': [62, 64],
 'RMX Mario Circuit 1R': [77, 104],
 'RMX Mario Circuit 1R/T': [24],
 'RMX Mario Circuit 1T': [57, 99],
 'RMX Rainbow Road 1': [108, 111],
 'RMX Rainbow Road 1R': [66, 113],
 'RMX Rainbow Road 1R/T': [],
 'RMX Rainbow Road 1T': [28, 82],
 'RMX Rainbow Road 2': [],
 'RMX Rainbow Road 2R': [],
 'RMX Rainbow Road 2T': [120],
 'SNES Choco Island 1': [],
 'SNES Choco Island 1R': [],
 'SNES Choco Island 1T': [],
 'SNES Choco Island 2': [35, 55],
 'SNES Choco Island 2R': [],
 'SNES Choco Island 2R/T': [3, 4],
 'SNES Choco Island 2T': [],
 'SNES Donut Plains 1': [48],
 'SNES Donut Plains 1R': [43],
 'SNES Donut Plains 1R/T': [39, 70],
 'SNES Donut Plains 1T': [67],
 'SNES Donut Plains 2': [91, 92],
 'SNES Donut Plains 2R': [],
 'SNES Donut Plains 2R/T': [95],
 'SNES Donut Plains 2T': [90],
 'SNES Ghost Valley 1': [71, 105],
 'SNES Ghost Valley 1R': [53],
 'SNES Ghost Valley 1R/T': [87],
 'SNES Ghost Valley 1T': [52],
 'SNES Koopa Troopa Beach 2': [76, 81],
 'SNES Koopa Troopa Beach 2R': [],
 'SNES Koopa Troopa Beach 2T': [63],
 'SNES Mario Circuit 1': [54, 89, 94],
 'SNES Mario Circuit 1R': [52],
 'SNES Mario Circuit 1R/T': [97],
 'SNES Mario Circuit 1T': [],
 'SNES Mario Circuit 2': [30, 61],
 'SNES Mario Circuit 2R': [],
 'SNES Mario Circuit 2R/T': [25, 38],
 'SNES Mario Circuit 2T': [31],
 'SNES Mario Circuit 3': [67, 75],
 'SNES Mario Circuit 3R': [42],
 'SNES Mario Circuit 3R/T': [],
 'SNES Mario Circuit 3T': [22],
 'SNES Rainbow Road': [51],
 'SNES Rainbow Road R': [83, 88],
 'SNES Rainbow Road R/T': [],
 'SNES Rainbow Road T': [115],
 'SNES Vanilla Lake 1': [],
 'SNES Vanilla Lake 1R': [47, 68],
 'SNES Vanilla Lake 1R/T': [1],
 'SNES Vanilla Lake 1T': [64, 82],
 'Sydney Sprint': [],
 'Sydney Sprint R': [],
 'Sydney Sprint R/T': [],
 'Sydney Sprint T': [],
 'Tokyo Blur': [],
 'Tokyo Blur 2': [],
 'Tokyo Blur 2R': [],
 'Tokyo Blur 2R/T': [],
 'Tokyo Blur 2T': [],
 'Tokyo Blur 3': [],
 'Tokyo Blur 3R': [],
 'Tokyo Blur 3T': [],
 'Tokyo Blur 4': [],
 'Tokyo Blur 4R': [],
 'Tokyo Blur 4R/T': [94],
 'Tokyo Blur 4T': [],
 'Tokyo Blur R': [],
 'Tokyo Blur R/T': [],
 'Tokyo Blur T': [],
 'Vancouver Velocity': [],
 'Vancouver Velocity R': [],
 'Vancouver Velocity R/T': [],
 'Vancouver Velocity T': [],
 'Wii DK Summit': [96],
 'Wii DK Summit R': [93],
 'Wii DK Summit T': [],
 'Wii Maple Treeway': [114, 115],
 'Wii Maple Treeway R': [],
 'Wii Maple Treeway T': [84]}

In [71]:
# Create a dataframe
level_six_df = pd.DataFrame.from_dict(level_6_top_shelf_driver, orient='index')
level_six_df

                                0      1   2   3
3DS Cheep Cheep Lagoon       60.0  106.0 NaN NaN
3DS Cheep Cheep Lagoon R      NaN    NaN NaN NaN
3DS Cheep Cheep Lagoon R/T   10.0   83.0 NaN NaN
3DS Cheep Cheep Lagoon T     70.0  103.0 NaN NaN
3DS Daisy Hills               NaN    NaN NaN NaN
...                           ...    ...  ..  ..
Wii DK Summit R              93.0    NaN NaN NaN
Wii DK Summit T               NaN    NaN NaN NaN
Wii Maple Treeway           114.0  115.0 NaN NaN
Wii Maple Treeway R           NaN    NaN NaN NaN
Wii Maple Treeway T          84.0    NaN NaN NaN

[222 rows x 4 columns]

In [72]:
# Make dataframe prettier
level_six_df = level_six_df.rename_axis("course_name")
level_six_df = level_six_df.rename(columns={0:"driver_id_1",1:"driver_id_2",2:"driver_id_3",3:"driver_id_4"})
level_six_df

                            driver_id_1  driver_id_2  driver_id_3  driver_id_4
course_name
3DS Cheep Cheep Lagoon             60.0        106.0          NaN          NaN
3DS Cheep Cheep Lagoon R            NaN          NaN          NaN          NaN
3DS Cheep Cheep Lagoon R/T         10.0         83.0          NaN          NaN
3DS Cheep Cheep Lagoon T           70.0        103.0          NaN          NaN
3DS Daisy Hills                     NaN          NaN          NaN          NaN
...                                 ...          ...          ...          ...
Wii DK Summit R                    93.0          NaN          NaN          NaN
Wii DK Summit T                     NaN          NaN          NaN          NaN
Wii Maple Treeway                 114.0        115.0          NaN          NaN
Wii Maple Treeway R                 NaN          NaN          NaN          NaN
Wii Maple Treeway T                84.0          NaN          NaN          NaN

[222 rows x 4 columns]

In [74]:
# Count NaN values per column
level_six_df.isna().sum()

driver_id_1     98
driver_id_2    166
driver_id_3    213
driver_id_4    220
dtype: int64

In [75]:
# Drop rows with NaN in driver_id_1 and check that they were dropped
level_six_df = level_six_df.dropna(subset=["driver_id_1"])
level_six_df.isna().sum()

driver_id_1      0
driver_id_2     68
driver_id_3    115
driver_id_4    122
dtype: int64

In [88]:
# Drop remaining columnds with NaN values
level_six_df = level_six_df.drop(columns=["driver_id_2","driver_id_3","driver_id_4"])
level_six_df

                            driver_id_1
course_name
3DS Cheep Cheep Lagoon             60.0
3DS Cheep Cheep Lagoon R/T         10.0
3DS Cheep Cheep Lagoon T           70.0
3DS Daisy Hills R/T                 7.0
3DS Mario Circuit R                17.0
...                                 ...
Tokyo Blur 4R/T                    94.0
Wii DK Summit                      96.0
Wii DK Summit R                    93.0
Wii Maple Treeway                 114.0
Wii Maple Treeway T                84.0

[124 rows x 1 columns]

In [ ]:
# EXPORT DATAFRAMES TO CSV

In [89]:
level_one_df.to_csv("level_one_top_shelf_drivers.csv")
level_three_df.to_csv("level_three_top_shelf_drivers.csv")
level_six_df.to_csv("level_six_top_shelf_drivers.csv")